# Generated by Django 5.0 on 2023-12-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(help_text='Телефон', max_length=11, unique=True, verbose_name='Телефон')),
                ('tg_id', models.CharField(help_text='telegram id', max_length=100, unique=True, verbose_name='telegram id')),
                ('name', models.CharField(help_text='Имя', max_length=254, verbose_name='Имя')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Вопрос', unique=True, verbose_name='Вопрос')),
                ('answer', models.TextField(help_text='Ответ', verbose_name='Ответ')),
                ('order', models.SmallIntegerField(help_text='Порядок вывода', verbose_name='Порядок вывода')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
