# Generated by Django 5.0 on 2023-12-27 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Категория",
                        max_length=100,
                        unique=True,
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email",
                        max_length=254,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Телефон",
                        max_length=11,
                        unique=True,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "tg_id",
                    models.CharField(
                        help_text="telegram id",
                        max_length=100,
                        unique=True,
                        verbose_name="telegram id",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Имя", max_length=254, verbose_name="Имя"
                    ),
                ),
                (
                    "registration_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата регистрации"
                    ),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.TextField(
                        help_text="Вопрос", unique=True, verbose_name="Вопрос"
                    ),
                ),
                ("answer", models.TextField(help_text="Ответ", verbose_name="Ответ")),
                (
                    "order",
                    models.SmallIntegerField(
                        help_text="Порядок вывода", verbose_name="Порядок вывода"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Категория",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="app.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Часто задаваемые вопросы",
                "verbose_name_plural": "Часто задаваемые вопросы",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="Messages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True,
                        max_length=4096,
                        null=True,
                        verbose_name="Текст сообщения от администратора",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="message_images/",
                        verbose_name="Фотография",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "selected",
                    models.BooleanField(
                        default=False,
                        verbose_name="Дополнить планировщик сообщением от администратора",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "ordering": ("id",),
            },
        ),
    ]
