# Generated by Django 5.0 on 2023-12-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='', help_text='Email', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default='', help_text='Имя', max_length=254, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='', help_text='Телефон', max_length=11, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tg_id',
            field=models.CharField(default='', help_text='telegram id', max_length=100, unique=True, verbose_name='telegram id'),
        ),
    ]
