# Generated by Django 5.0 on 2023-12-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customer_email_alter_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tg_id',
            field=models.CharField(default=None, help_text='telegram id', max_length=100, unique=True, verbose_name='telegram id'),
        ),
    ]
