# Generated by Django 5.0 on 2023-12-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customer_tg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tg_id',
            field=models.CharField(help_text='telegram id', max_length=100, unique=True, verbose_name='telegram id'),
        ),
    ]
