# Generated by Django 5.0 on 2023-12-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_customer_tg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='', help_text='Email', max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
