# Generated by Django 5.0 on 2023-12-22 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_customer_options_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('id',), 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
    ]
