# Generated by Django 5.0 on 2023-12-22 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_customer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ('order',), 'verbose_name': 'ЧаВо', 'verbose_name_plural': 'ЧаВо'},
        ),
    ]
