# Generated by Django 5.0 on 2023-12-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_alter_customer_options_alter_faq_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq",
            name="category",
            field=models.CharField(
                choices=[
                    ("DONATION", "Пожертвование"),
                    ("GUARDIANS", "Опекунство"),
                    ("ABOUT_US", "О нас"),
                    ("PROGRAMS", "Программы"),
                    ("GENERAL", "Общие вопросы"),
                ],
                default="GENERAL",
                max_length=10,
                verbose_name="Категория",
            ),
        ),
    ]
