# Generated by Django 5.0 on 2023-12-22 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_alter_faq_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Messages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True,
                        max_length=4096,
                        null=True,
                        verbose_name="Текст сообщения от администратора",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="message_images/",
                        verbose_name="Фотография",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "selected",
                    models.BooleanField(
                        default=False,
                        verbose_name="Дополнить планировщик сообщением от администратора",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.customer",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Сообщения",
            },
        ),
    ]
