# Generated by Django 5.0 on 2023-12-25 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_faq_category'),
        ('app', '0009_messages'),
    ]

    operations = [
    ]
