# Generated by Django 5.0 on 2023-12-25 16:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_merge_0008_alter_faq_category_0009_messages"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="messages",
            options={
                "ordering": ("id",),
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
    ]
